# -*- mode: ruby -*-
# vi: set ft=ruby :

domain = "demo.internal"
master = "puppet"
base_ip = "192.168.13."
pm_ip = base_ip + "10"

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  # windows - has to be handled differently
  config.vm.define 'windows' do |v|
    v.vm.box = "windows-server-2012r2-v3"
    v.vm.guest = :windows
    v.vm.communicator = "winrm"
    v.ssh.insert_key = false
    v.vm.network "private_network", ip: "192.168.13.250"
    v.vm.hostname = "windows2012"

    config.vm.provider :virtualbox do |vb|
      vb.gui = true
      vb.customize ["modifyvm", :id, "--memory", 1024]
      vb.customize ["modifyvm", :id, "--cpus", 1]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end 
  end


  # add puppmaster to every VMs hosts file
  config.vm.provision :hosts do |provisioner|
    provisioner.add_host pm_ip, ["#{master}.#{domain}", master, 'puppet']
  end

end
